added gatsby-source-filesystem and replaced logo with a GatsbyImage
alexadark/atsg pull request #56
Opened 2021-05-28 01:51 UTC by Renesauve

explicit width + height not on image error

#20 

I fixed this on homepage logo although there's more on other pages, still going after them

2021-05-30 23:25 UTC, Renesauve commented
Hey! this should be all good now, I went through every page so hopefully I got them all :D

2021-05-31 18:48 UTC, carlosloureda commented on site/src/components/header/SiteBranding.js
> +              placeholder: BLURRED
The blurred effect hurts visually the visitor's eye. @Renesauve which are the possibilities to show the logo faster but with better quality?

Also check mobile, it is too big:



![bad-logo-mobile](https://user-images.githubusercontent.com/1656532/120231324-6d7d4d80-c251-11eb-9e57-5b7c771f3f22.png)


Nice improvement on **accesibility**!
![Screenshot from 2021-05-31 20-48-10](https://user-images.githubusercontent.com/1656532/120231382-96054780-c251-11eb-9e62-61e5556e7c3b.png)

2021-05-31 18:50 UTC, carlosloureda requested changes
Everything looks awesome but we need to improve the logo image on the header on mobile and also can we improve the first rendering of it?

Thanka! Great work :muscle:

2021-05-31 19:09 UTC, Renesauve commented on site/src/components/header/SiteBranding.js
> +              placeholder: BLURRED
Ah yes! I will fix this, I overlooked mobile, good thing you checked!

2021-05-31 19:15 UTC, carlosloureda commented on site/src/components/header/SiteBranding.js
> +              placeholder: BLURRED
It was while running the ligthhouse that i saw it :D. Also check the blurry effect on load (if we can make something better, Roberto won't like that as it is strange). Let me know your thoughts

2021-05-31 21:47 UTC, Renesauve commented
this should be fixed now,

All of our options for the image loading are "TRACED_SVG, BLURRED, DOMINANT_COLOR, or NONE"

I think the TRACED_SVG looks the best but it's up to Robert

2021-06-01 08:56 UTC, carlosloureda approved these changes
Great job. Taking it to dev

2021-06-01 08:57 UTC, merged